name: deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
# on:
#   # we can also trigger manually in case needed
#   workflow_dispatch:

jobs:
  deploy:
    name: Build On X64
    runs-on: [ "self-hosted"]
    permissions:
      # Need this to be allowed to publish image to registry
      # see https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: deploy
        run: |
          docker compose -f docker-compose.yml up -d