name: deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildImage:
    name: build test
    runs-on: [ "wade"]
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag server:latest
  deploy:
    needs: buildImage
    name: deploy test
    runs-on: [ "self-hosted"]
    permissions:
      # Need this to be allowed to publish image to registry
      # see https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: deploy
        run: |
          docker compose -f docker-compose.yml up -d